nxos/base/drivers/avr: Suppress fallthrough warning.
This appears to be intentional since mode is set to AVR_RECV, so do not add a break statement.

Fixes:

base/drivers/avr.c: In function 'nx__avr_fast_update':
base/drivers/avr.c:305:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
  305 |     if (nx__twi_ready()) {
      |        ^
base/drivers/avr.c:312:3: note: here
  312 |   case AVR_RECV:
      |   ^~~~